---
- name: "Install vim"
  package:
    name: vim
    state: present

- name: "Set vim as default editor"
  alternatives:
    name: editor
    path: /usr/bin/vim

- name: "Set global vimrc"
  template:
    src: vimrc.local.j2
    dest: /etc/vim/vimrc.local
    owner: root
    group: root
    mode: 0644